# Generated by Django 3.2.3 on 2021-05-28 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendanceclass',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'verbose_name_plural': 'Marks'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='shortname',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sex',
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(default='1998-01-01'),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='CSE', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.CharField(default='ABC@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='DOB',
            field=models.DateField(default='1980-01-01'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='branch',
            field=models.CharField(default='CSE', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mail',
            field=models.CharField(default='ABC@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('8:00 - 8:50', '8:00 - 8:50'), ('8:55 - 9:45', '8:55 - 9:45'), ('9:50 - 10:40', '9:50 - 10:40'), ('10:45 - 11:35', '10:45 - 11:35'), ('11:35 - 12:30', '11:35 - 12:30'), ('12:30 - 1:20', '12:30 - 1:20'), ('2:00 - 2:50', '2:00 - 2:50'), ('2:55 - 3:45', '2:55 - 3:45'), ('3:45 - 4:40', '3:45 - 4:40'), ('4:45 - 5:35', '4:45 - 5:35'), ('5:45 - 6:30', '5:45 - 6:30')], default='11:00 - 11:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('CAT 1', 'CAT 1'), ('CAT 2', 'CAT 2'), ('FAT', 'FAT')], default='Internal test 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('CAT 1', 'CAT 1'), ('CAT 2', 'CAT 2'), ('FAT', 'FAT')], default='Internal test 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.dept'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterUniqueTogether(
            name='assign',
            unique_together={('course', 'class_id', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancetotal',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('studentcourse', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='marksclass',
            unique_together={('assign', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student', 'course')},
        ),
    ]
