# Generated by Django 3.2.3 on 2021-05-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210530_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sex',
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='CSE', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.CharField(default='ABC@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='branch',
            field=models.CharField(default='CSE', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mail',
            field=models.CharField(default='ABC@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('8:00 - 8:50', '8:00 - 8:50'), ('8:55 - 9:45', '8:55 - 9:45'), ('9:50 - 10:40', '9:50 - 10:40'), ('10:45 - 11:35', '10:45 - 11:35'), ('11:35 - 12:30', '11:35 - 12:30'), ('12:30 - 1:20', '12:30 - 1:20'), ('2:00 - 2:50', '2:00 - 2:50'), ('2:55 - 3:45', '2:55 - 3:45'), ('3:45 - 4:40', '3:45 - 4:40'), ('4:45 - 5:35', '4:45 - 5:35'), ('5:45 - 6:30', '5:45 - 6:30')], default='11:00 - 11:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('CAT 1', 'CAT 1'), ('CAT 2', 'CAT 2'), ('FAT', 'FAT')], default='Internal test 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('CAT 1', 'CAT 1'), ('CAT 2', 'CAT 2'), ('FAT', 'FAT')], default='Internal test 1', max_length=50),
        ),
    ]
