# Generated by Django 3.2.3 on 2021-06-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20210530_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('8:00 - 8:50', '8:00 - 8:50'), ('8:55 - 9:45', '8:55 - 9:45'), ('9:50 - 10:40', '9:50 - 10:40'), ('10:45 - 11:35', '10:45 - 11:35'), ('11:35 - 12:30', '11:35 - 12:30'), ('12:30 - 1:20', '12:30 - 1:20'), ('2:00 - 2:50', '2:00 - 2:50'), ('2:55 - 3:45', '2:55 - 3:45'), ('3:45 - 4:40', '3:45 - 4:40'), ('4:45 - 5:35', '4:45 - 5:35'), ('5:45 - 6:30', '5:45 - 6:30')], default='8:00 - 8:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2021-06-11'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('CAT 1', 'CAT 1'), ('CAT 2', 'CAT 2'), ('FAT', 'FAT')], default='CAT 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('CAT 1', 'CAT 1'), ('CAT 2', 'CAT 2'), ('FAT', 'FAT')], default='CAT 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(default='2003-01-01'),
        ),
    ]
